name: PortalPlugin
main: com.blake.portalplugin.PortalPlugin
version: 1.0.0
api-version: '1.20'
author: Blake

commands:

  gamestate:
    description: View or set your game state
    usage: /gamestate [HUB|ARENA|SPLEEF|ADMIN]

  fillhunger:
    description: Fill your hunger bar
    usage: /fillhunger

  fillhealth:
    description: Fill your health bar
    usage: /fillhealth

  arena:
    description: Manage arenas
    usage: |
      /arena add <name>
      /arena spawn <name> <x> <y> <z>
      /arena save <name> <material> <x1> <y1> <z1> <x2> <y2> <z2>

  creategame:
    description: Create a new game queue
    usage: /creategame <game>

  join:
    description: Join or leave a game queue
    usage: /join <game>

  createsign:
    description: Create a sign that joins/leaves a queue
    usage: /createsign <game>

  createspawnsign:
    description: Create a sign that teleports players to spawn
    usage: /createspawnsign
    permission: portalplugin.createspawnsign

  clearsigns:
    description: Destroy all registered queue signs and reset saved sign locations
    usage: /clearsigns
    permission: portalplugin.clearsigns

  arenamaximum:
    description: Set maximum players for an arena
    usage: /arenamaximum <arena> <number>

  setspawn:
    description: Set the hub spawn location
    usage: /setspawn <x> <y> <z>

  stats:
    description: View your game statistics
    usage: /stats
    permission: portalplugin.stats

  createscoreboard:
    description: Create a floating leaderboard hologram
    usage: /createscoreboard <gamemode> wins
    permission: portalplugin.createscoreboard

  gameset:
    description: Set the active game for this server (persistent across restarts)
    usage: /gameset <gamemode>
    permission: portalplugin.gameset

  currency:
    description: View or modify your currency
    usage: /currency
    permission: portalplugin.currency

  rank:
    description: View or set your rank
    usage: /rank [rank]
    permission: portalplugin.rank

  gamewinloc:
    description: Set the global win teleport location
    usage: /gamewinloc <x> <y> <z>
    permission: portalplugin.winlocation

  pos1:
    description: Set region position 1 (target block or /pos1 x y z)
    usage: /pos1 [x y z]
    permission: portalplugin.worldedit

  pos2:
    description: Set region position 2 (target block or /pos2 x y z)
    usage: /pos2 [x y z]
    permission: portalplugin.worldedit

  pfill:
    description: Fill selected region with a block (optionally only replace a specific block)
    usage: /pfill <block> [onlyReplaceBlock]
    permission: portalplugin.worldedit

  pclear:
    description: Clear selected region (optionally only clear a specific block)
    usage: /pclear [onlyReplaceBlock]
    permission: portalplugin.worldedit

  # NEW: copy/paste/rotate/flip (WorldEdit-like)
  pcopy:
    description: Copy selected region to your clipboard
    usage: /pcopy
    permission: portalplugin.worldedit

  ppaste:
    description: Paste your clipboard at your target block (or coords). Use -a to skip air.
    usage: |
      /ppaste
      /ppaste -a
      /ppaste [ -a ] <x> <y> <z>
    permission: portalplugin.worldedit

  protate:
    description: Rotate your clipboard (90/180/270)
    usage: /protate [90|180|270]
    permission: portalplugin.worldedit

  pflip:
    description: Flip your clipboard on X or Z axis
    usage: /pflip <x|z>
    permission: portalplugin.worldedit

  hubtype:
    description: Set this server's hub type (arena or minigame)
    usage: /hubtype <arena|minigame>
    permission: portalplugin.hubtype

  setminigame:
    description: Set the server minigame (for hub-type=minigame)
    usage: /setminigame <game>
    permission: portalplugin.setminigame

  blastregen:
    description: Regenerate a BLAST map by pasting its schematic (WorldEdit/FAWE required)
    usage: |
      /blastregen [map]
      /blastregen list
      /blastregen reload
    permission: portalplugin.blast.regen

  blastmap:
    description: Create/save/regenerate BLAST maps (region + spawns)
    usage: |
      /blastmap list
      /blastmap create <name>
      /blastmap saveregion <name>
      /blastmap setpaste <name>
      /blastmap setspawn <name> <red|green|yellow|blue> <1-4>
      /blastmap startspawn <name> <x> <y> <z>
      /blastmap select <name>
      /blastmap regen <name>
      /blastmap info <name>
    permission: portalplugin.blast.maps

  spawnprotection:
    description: Set BLAST spawn protection region for a team
    usage: /spawnprotection <team> <x1> <y1> <z1> <x2> <y2> <z2>
    permission: portalplugin.blast.spawnprotection

  diamondspawnrange:
    description: Set the BLAST diamond spawn Y range
    usage: /diamondspawnrange <minY> <maxY>
    permission: portalplugin.blast.diamondspawnrange

  pausecountdown:
    description: Pause the BLAST queue countdown
    usage: /pausecountdown
    permission: portalplugin.blast.countdown

  resumecountdown:
    description: Resume the BLAST queue countdown
    usage: /resumecountdown
    permission: portalplugin.blast.countdown

  restartcountdown:
    description: Restart the BLAST queue countdown back to 30 seconds
    usage: /restartcountdown
    permission: portalplugin.blast.countdown

permissions:

  portalplugin.stats:
    description: Allows use of /stats
    default: true

  portalplugin.createscoreboard:
    description: Allows use of /createscoreboard
    default: op

  portalplugin.gameset:
    description: Allows use of /gameset to set the active server game
    default: op

  portalplugin.currency:
    description: Allows use of /currency
    default: true

  portalplugin.currency.admin:
    description: Allows modifying others' currency
    default: op

  portalplugin.clearsigns:
    description: Allows clearing all queue signs
    default: op

  portalplugin.rank:
    description: Allows viewing own rank
    default: true

  portalplugin.rank.set:
    description: Allows setting ranks
    default: op

  portalplugin.winlocation:
    description: Allows setting the global win location
    default: op

  portalplugin.blast.diamondspawnrange:
    description: Allows setting the BLAST diamond spawn Y range
    default: op

  portalplugin.createspawnsign:
    description: Allows creating spawn signs
    default: op

  portalplugin.worldedit:
    description: Allows using /pos1, /pos2, /pfill, /pclear, /pcopy, /ppaste, /protate, /pflip
    default: op

  portalplugin.worldedit.bypasslimit:
    description: Bypass worldedit.max-blocks limit for region edits
    default: op

  portalplugin.hubtype:
    description: Allows changing hub type
    default: op

  portalplugin.setminigame:
    description: Allows setting server-minigame
    default: op

  portalplugin.blast.regen:
    description: Allows regenerating BLAST maps from schematics
    default: op

  portalplugin.blast.maps:
    description: Allows managing BLAST maps (save region, set spawns, regen)
    default: op

  portalplugin.blast.spawnprotection:
    description: Allows setting BLAST spawn protection regions
    default: op

  portalplugin.blast.countdown:
    description: Allows pausing/resuming/restarting the BLAST queue countdown
    default: op
